### ISSUE TITLE
Dynamically loading class com.couchbase.lite.store.SQLiteViewStore$AbstractMapEmitBlock was unsuccessful. Will attempt to load class from alternative ClassLoader

### ISSUE THREAD

**Issue by aboganas** [couchbaselabs/nativescript-couchbase#67]
Every time i do `executeQuery` I get the following error

`JS: Dynamically loading class com.couchbase.lite.store.SQLiteViewStore$AbstractMapEmitBlock was unsuccessful. Will attempt to load class from alternative ClassLoader.`

Is this error something I should be worry about or is it just a warning

**Comment by attdona** [comment]
Probably I hit the same problem, or a missing piece of knowledge:

    Successfully synced application org.nativescript.bocianative on device emulator-5554.
    ActivityManager: Start proc 3420:org.nativescript.bocianative/u0a83 for activity 
    org.nativescript.bocianative/com.tns.NativeScriptActivity
    JS: Dynamically loading class com.couchbase.lite.store.SQLiteViewStore$AbstractMapEmitBlock was 
    unsuccessful. Will attempt to load class from alternative ClassLoader.
    01-03 12:27:57.638  3420  3420 E View    : SyntaxError: Unexpected token o in JSON at position 1
    01-03 12:27:57.638  3420  3420 E View    : 	at com.tns.Runtime.callJSMethodNative(Native Method)
    01-03 12:27:57.638  3420  3420 E View    : 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)

Test code from https://blog.couchbase.com/couchbase-mobile-in-a-cross-platform-telerik-nativescript-app/

    var couchbaseModule = require("nativescript-couchbase");
    var observableArrayModule = require("data/observable-array"); 
    var frameModule = require("ui/frame");

    var database;
    var personList;

    function pageLoaded(args) {
     var page = args.object;

     personList = new observableArrayModule.ObservableArray([]);
     database = new couchbaseModule.Couchbase("test-database");

     database.createView("people", "1", function(document, emitter) {
        emitter.emit(JSON.parse(document)._id, document);
     });

      refresh();
      page.bindingContext = {personList: personList};
    }

    function refresh() {
      personList.splice(0);

      var rows = database.executeQuery("people");

      for(var i in rows) {
          if(rows.hasOwnProperty(i)) {
              personList.push(JSON.parse(rows[i]));
          }
      }
    }

    function create() {
      frameModule.topmost().navigate({moduleName: "views/create/create"});
    }

    exports.pageLoaded = pageLoaded;
    exports.refresh = refresh;
    exports.create = create;

![screenshot](https://user-images.githubusercontent.com/943963/34519377-f7817d88-f083-11e7-8d03-0d0b92072041.png)

**Comment by attdona** [comment]
After some more investigation my conclusion is that the quite obscure (for me) error:

     JS: Dynamically loading class com.couchbase.lite.store.SQLiteViewStore$AbstractMapEmitBlock was unsuccessful. Will attempt to load class from alternative ClassLoader.

is not meaningful. Instead the error:

    01-03 12:27:57.638  3420  3420 E View    : SyntaxError: Unexpected token o in JSON at position 1

pointed me in the right direction:

    function refresh() {
        personList.splice(0);

        var rows = database.executeQuery("people");

        for(var i in rows) {
            if(rows.hasOwnProperty(i)) {
                //personList.push(JSON.parse(rows[i]));   <--- ERROR CAUSE
                personList.push(rows[i]);
            }
        }
    }

**Comment by Sha-Grisha** [comment]
I have the same issue 
`Dynamically loading class com.couchbase.lite.store.SQLiteViewStore$AbstractMapEmitBlock was unsuccessful. Will attempt to load class from alternative ClassLoader.`
On any database.executeQuery.

At the same time createView, createDocument, getDocument(id) - works fine...
