### ISSUE TITLE
PullReplication does not work with https on Android

### ISSUE THREAD

**Issue by RobinJespersen** [couchbaselabs/nativescript-couchbase#72]
I created a pull replication from an couchdb (2.1) to a local database.
The remote db is accessible via https (Let's Encrypt certificate).

The replication works great on iOS but not on Android. 

I installed the same remote db on another domain without https enabled.
Then replication works on Android but no longer on iOS.

I know that iOS requires https and that is fine but I can't find the reason why https on Android is not working.
https://developer.apple.com/news/?id=12212016b

**Comment by nraboy** [comment]
> I created a pull replication from an couchdb (2.1) to a local database.

This plugin is for Couchbase, which is totally unrelated to CouchDB. Could that be the problem?

**Comment by RobinJespersen** [comment]
No, this should not be the Problem.

> Couchbase Lite's replication protocol is compatible with Apache CouchDB.
https://github.com/couchbase/couchbase-lite-ios/wiki/Replication-Algorithm

**Comment by RobinJespersen** [comment]
To be 100% sure I tried to sync with a couchbase (docker couchbase/sync-gateway) via https.
iOS is working Android is not.

**Comment by RobinJespersen** [comment]
I tried to sync a native Android App (https://github.com/couchbaselabs/GrocerySync-Android) and that worked.

Then I updated in the build.gradle
`    compile 'com.couchbase.lite:couchbase-lite-android:0.0.0-679'
`
to
`    compile 'com.couchbase.lite:couchbase-lite-android:1.3.1'
`

and it stoped working.
```

Sync error: java.net.ProtocolException: Expected ':status' header not present
                                                                      java.net.ProtocolException: Expected ':status' header not present
                                                                          at okhttp3.internal.http.Http2xStream.readHttp2HeadersList(Http2xStream.java:267)
                                                                          at okhttp3.internal.http.Http2xStream.readResponseHeaders(Http2xStream.java:150)
                                                                          at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775)
                                                                          at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
                                                                          at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
                                                                          at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
                                                                          at okhttp3.RealCall.getResponse(RealCall.java:244)
                                                                          at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
                                                                          at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
                                                                          at okhttp3.RealCall.execute(RealCall.java:57)
                                                                          at com.couchbase.lite.replicator.RemoteRequest.executeRequest(RemoteRequest.java:250)
                                                                          at com.couchbase.lite.replicator.RemoteRequest.execute(RemoteRequest.java:165)
                                                                          at com.couchbase.lite.replicator.RemoteRequest.run(RemoteRequest.java:105)
                                                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                          at java.lang.Thread.run(Thread.java:761)

```

so the problem is in couchbase-lite-android

**Comment by RobinJespersen** [comment]
https://github.com/couchbase/couchbase-lite-android/issues/1481
